### ISSUE TITLE
Bug of export_ply.h

### ISSUE THREAD

**Issue by KenjiFukuda** [cnr-isti-vclab/vcglib#1]
vcg::tri::io::ExporterPLY\<T\>::Save function in /vcglib/wrap/io_trimesh/export_ply.h doesn't work correctly when ply has mesh and texture and is ascii format.  Output ply file has broken texture.

Now line 562  is
                                for(int k=0;k<fp->VN()*2;++k)
I guess it should be
                                for (int k=0;k<fp->VN();++k)

**Comment by granzuglia** [comment]
hi Kenji, 
the bug was already fixed in our github/develop branch. thanks anyway for the help you provided us and for the you will wish to provide us also in the future :)



Sent from my Wiko FEVERIl 03/ago/2016 02:27 KenjiFukuda <notifications@github.com> ha scritto:

**Comment by KenjiFukuda** [comment]
hi granzuglia.

ok.
Thank you for your reply.
