### ISSUE TITLE
Some bugs and suggestions?

### ISSUE THREAD

**Issue by jiapei100** [cnr-isti-vclab/vcglib#11]
Hi, My Env:
OS: Ubuntu 16.04.1
GCC: 5.4.0

Bugs found so far:

1.  ```
.../vcglib/apps/sample/trimesh_voronoisampling/trimesh_voronoisampling.cpp:123: error: ‘FixVertexVector’ is not a member of ‘vcg::tri::VoronoiProcessing<MyMesh>’
       tri::VoronoiProcessing<MyMesh, tri::EuclideanDistance<MyMesh> >::FixVertexVector(baseMesh,fixedSeedVec);
       ^
```

2. ```
.../vcglib/vcg/simplex/vertex/base.h:24: error: #error "This file should not be included alone. It is automatically included by complex.h"
 #error "This file should not be included alone. It is automatically included by complex.h"
  ^
```

3. ```
/usr/local/include/vcg/simplex/vertex/base.h:24: error: #error "This file should not be included alone. It is automatically included by complex.h"
 #error "This file should not be included alone. It is automatically included by complex.h"
  ^
```

4. ```
.../vcglib/apps/quadrangulator/quadrangulator.cpp:142: error: ‘MIQ_parametrization’ was not declared in this scope
     if (! MIQ_parametrization<CMesh>::IsValid(trimesh) )
           ^
```

Suggestions:

- Do Not use "using namespace std;", instead, use "std::"? Other namespace the same...

- Give a more specific example for how to use the **complex.h** ? I did get a lot of ERROR messages as the above mentioned bug 3.

Thank you very much
Cheers
Pei

**Comment by cignoni** [comment]
Please, look at the examples in the app/samples folder and at the explanations on http://www.vcglib.net
