### ISSUE TITLE
Doesn't compile on Linux

### ISSUE THREAD

**Issue by facontidavide** [cnr-isti-vclab/vcglib#16]
Hi,

I am trying to make the samples compile on Linux but it is being very hard to fix the large amount of error...
I am using gcc 4.8 and QtCreator 5.7.1

**Comment by cignoni** [comment]
After the last set of commits (a597aea988d8de9888ff1e46008f005e764abd72 4fb89211304d3cfca0bea23e085cf06c988121f4 5a29812d7bb685e2de9d5aeadf71329ee9e63e14 ) Current set of samples listed in the apps/sample/sample.pro
should correctly compile now. Sorry for the error.
