### ISSUE TITLE
HETYPE  in simplex/tetrahedron/pos.h unexpected token

### ISSUE THREAD

**Issue by Cervidellus** [cnr-isti-vclab/vcglib#168]
Trying to compile a simple application that loads a mesh with importerOBJ  in visual studio 2019. 

I get several errors, some of them I ignore as they relate to things that are deprecated in c++14 and removed from c++17 (strcpy, std::unary_function). 

But I also get a C2760 "syntax error:unexpected token 'identifier', expected ';' 
coming from line 383 of pos.h. 

There it declares a HETYPE ht=*this;

I can't figure out where HETYPE is defined?  Or how to get my code to compile with it there?

**Comment by alemuntoni** [comment]
The library right now supports only c++11, sorry. 

About HETYPE, I really don't know what it is and why is it there, but it seems that can be ignored by not defining the _DEBUG macro, which is defined by visual studio when compiling with debug symbols.

**Comment by SimonNgj** [comment]
I commented all of this function and it worked

**Comment by satyajitghana** [comment]
`-DCMAKE_BUILD_TYPE=Release` fixed it
