### ISSUE TITLE
Have the tri_edge_collapse_quadric.h example?

### ISSUE THREAD

**Issue by for-heart-peace** [cnr-isti-vclab/vcglib#170]
Hi~
I want to use tri_edge_collapse_quadric.h to simplify the models, but I can not find the way from the "apps/sample". Can you help me? Thank you very much!
Lingxin Cao

**Comment by malomo** [comment]
The algorithm is used in a meshlab decimation filter.
You can check the implementation and use it as example:
https://github.com/cnr-isti-vclab/meshlab/blob/f2c399ac8bff483ab661227c38dd09c82cff4d77/src/meshlabplugins/filter_meshing/quadric_simp.cpp
