### ISSUE TITLE
vcglib/apps/sample/trimesh_normal/trimesh_normal.cpp

### ISSUE THREAD

**Issue by SimonNgj** [cnr-isti-vclab/vcglib#173]
When I run this code, I got this error: 
Exception Unhandled 
Microsoft C++ exception: vcg::MissingComponenttException at memory location ... at base.h file
Anyone know how to solve this issue? Really appreciated any help

**Comment by SimonNgj** [comment]
![image](https://user-images.githubusercontent.com/22513384/127957566-0b52a88e-cfcc-4b3e-8c12-b4f1e3246646.png)

**Comment by SimonNgj** [comment]
It seems like all normal calculation methods presented in this program need "face". Is there any method to calculate the normals for points set when the input is just the x, y, and z of points (Vertices)?

**Comment by SimonNgj** [comment]
I found the source code of function "Filters\Normals, Curvatures and Orientation\Compute normals for point set" in meshlab-master\meshlab-master\src\meshlabplugins\filter_func

**Comment by PerspectivesLab** [comment]
you have to enable per face normals, mesh.face.enableNormal();
then you can apply filters is needed
