### ISSUE TITLE
Ball Pivoting: potentially uninitialized local pointer variable 'vv0', 'vv1', 'vv2' used

### ISSUE THREAD

**Issue by SimonNgj** [cnr-isti-vclab/vcglib#174]
When I run trimesh_ball_pivoting.cpp example, I got this error:
potentially uninitialized local pointer variable 'vv0', 'vv1', 'vv2' used
Anyone knows how to fix it?

**Comment by SimonNgj** [comment]
After I initialized all these three variable equal 0, it works
VertexType *vv0=0, *vv1=0, *vv2=0;

**Comment by alemuntoni** [comment]
Hi, 
please check your compiler flags, it is probably treating warnings as compiler errors.

**Comment by SimonNgj** [comment]
Actually it shows error when I Build Solution
