### ISSUE TITLE
Can not open mesh file

### ISSUE THREAD

**Issue by QingkaiLu** [cnr-isti-vclab/vcglib#18]
Hi, 

I am having trouble to load mesh file using vcglib. I tried trimesh_base under "/vcg/apps/sample/trimesh_base" to load my mesh file (tried both obj and ply formats), but it doesn't work. The error message is "Invalid file: OFF file should have in the first line the OFF keyword as a first token". The mesh file can be open in meshlab, so I assume the mesh file is correct. 

I also tried "vcg::tri::io::ImporterPLY<MyMesh>::Open", which doesn't compile for me. The compile error is: " undefined reference to `vcg::ply::PlyFile::AddToRead(char const*, char const*, int, int, unsigned long, int, int, int, int, unsigned long)' ".

Could anyone give me some suggestions to solve this? I couldn't find helpful information online. I appreciate the help in advance.

**Comment by cignoni** [comment]
To read ply files you need to use #include<wrap/io_trimesh/import.h>
 and to add the [plylib.cpp](https://github.com/cnr-isti-vclab/vcglib/blob/master/wrap/ply/plylib.cpp) file to the list of compiled files. See for example [the .pro file of the trimesh_color sample](https://github.com/cnr-isti-vclab/vcglib/blob/master/apps/sample/trimesh_color/trimesh_color.pro)

**Comment by amadou1998** [comment]
I have vcg sitting somewhere in /build/_deps. Where would I need to put the .pro in my project for this to work?
