### ISSUE TITLE
Exported OBJ materials are transparent instead of opaque

### ISSUE THREAD

**Issue by brettle** [cnr-isti-vclab/vcglib#213]
For opaque materials, Tr should be 0.0 not 1.0 (see [here](https://en.m.wikipedia.org/wiki/Wavefront_.obj_file#Basic_materials)). The problem appears to be here:

https://github.com/cnr-isti-vclab/vcglib/blob/e4950d12e2db7f6ec3e587b06b2a0474b4f08d96/wrap/io_trimesh/io_material.h#L103

**Comment by alemuntoni** [comment]
fixed! Thanks!
