### ISSUE TITLE
trimesh_curvature sample crashes

### ISSUE THREAD

**Issue by jnuevo** [cnr-isti-vclab/vcglib#25]
Hi,

The curvature sample crashes with:
Assertion failed: (0), function Kh, file ../../../vcg/simplex/vertex/component.h, line 140.
When called from  `vcg::tri::UpdateCurvature<MyMesh>::MeanAndGaussian(m);` in the sample code.

(There was a reference to this in an old thread in sourceforge, but a solution wasn't posted).

I'm compiling this without QMake, using instead `c++ -g -O0 -std=c++11 -Wall -isystem../../../ trimesh_curvature.cpp -o trimesh_curvature`, which compiles without any issue.

Cheers,
J

**Comment by cignoni** [comment]
corrected with commit 7f38262616002cbdd34db3f2a496ebd140fe86ed
