### ISSUE TITLE
GCC problems

### ISSUE THREAD

**Issue by animecomico** [cnr-isti-vclab/vcglib#3]
I Have problems in  GCC 4.9.3:
/usr/local/vcg/wrap/io_trimesh/import_obj.h:280:41: error: ‘Allocator’ is not a member of ‘vcg::tri’

How to fix this?
I can't fix this yet.

**Comment by cignoni** [comment]
When does this happen? Can you provide a minimal sample that trigger this error?

**Comment by animecomico** [comment]
Hi,

I solve my problem, in my code , place the following include:
#include <vcg/complex/complex.h>
#include <vcg/complex/allocate.h>

But now my problem is another:
This is my normal_extrapolation.h
[normal_extrapolation.txt](https://github.com/cnr-isti-vclab/vcglib/files/509273/normal_extrapolation.txt)
And this is my anysotropicPCA_Normal.h
[anistropicPCA_Normal.txt](https://github.com/cnr-isti-vclab/vcglib/files/509274/anistropicPCA_Normal.txt)
When try compile, i get this error:
Algorithm/anistropicPCA_Normal.h: In static member function 'static void AnistropicPca<VERTEX_CONTAINER>::SmoothNormalsUsingNeighbors(const VertexIterator&, const VertexIterator&, unsigned int, bool, bool (*)(int, const char*))':
/media/DATAL/ScarabVision/PointCloud/L1/Point Cloud/Algorithm/anistropicPCA_Normal.h:199:13: error: 'VertPointDistanceFunctor' was not declared in this scope
             VertPointDistanceFunctor vpdf;
             ^
/media/DATAL/ScarabVision/PointCloud/L1/Point Cloud/Algorithm/anistropicPCA_Normal.h:200:13: error: 'DummyObjectMarker' was not declared in this scope
             DummyObjectMarker dom;

I can't fixed yet.

**Comment by animecomico** [comment]
Hi, i fixed my problems.
Not problems with VCG, was my code.
