### ISSUE TITLE
UBSAN: undefined behaviour in vcg/complex/allocate.h 

### ISSUE THREAD

**Issue by zarquon42b** [cnr-isti-vclab/vcglib#30]
Hi,
I am the author of the R-package Rvcg based on vcglib. I get the following ubsan messages 
```
vcglib/vcg/complex/allocate.h:984:32: runtime error: addition of unsigned offset to 0x7f7f83c53800 overflowed to 0x7f7f83c53798
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior vcglib/vcg/complex/allocate.h:984:32 in 
vcglib/vcg/complex/allocate.h:1012:35: runtime error: addition of unsigned offset to 0x7f7f83c53800 overflowed to 0x7f7f83c53798
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior vcglib/vcg/complex/allocate.h:1012:35 in 
```
I cannot submit a new package version until this is fixed (I can patch my version of the code without bothering upstream. Any help would be highly appreciated.

**Comment by cignoni** [comment]
The error is happening in what branch? devel or master (in devel the line number does not seem very dangerous)
This runtime error always happens or only in some cases? Can you help me to replicate it?

**Comment by zarquon42b** [comment]
Hi, on master branch. I investigated further and the issue only seems to appear on CRAN's servers (https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/Rvcg/Rvcg-Ex.Rout) however I cannot reproduce it myself. Maybe it is a false positive. I will try to discuss this with the CRAN crew.

**Comment by zarquon42b** [comment]
Hi, on master branch. I investigated further and the issue only seems to appear on CRAN's servers (https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/Rvcg/Rvcg-Ex.Rout) however I cannot reproduce it myself. Maybe it is a false positive. I will try to discuss this possibility with the CRAN crew.

**Comment by zarquon42b** [comment]
I think I could convince them that it was a false positive, so I am going to close this issue.

**Comment by cignoni** [comment]
Ok,
I would be happier if you were able to reproduce it :) 
BTW thanks!

**Comment by zarquon42b** [comment]
Me too, stuff like this is bugging me and yesterday I spent the entire morning trying to reproduce it, using the docker container designed for this but to no avail. If it does not go away in the future, I will reopen the issue. I could however reproduce #32 immediately.
