### ISSUE TITLE
VCG_USE_EIGEN compiling error

### ISSUE THREAD

**Issue by khanhha** [cnr-isti-vclab/vcglib#45]
I am using vcglib for a research project relating to 3D reconstruction. I hope you can help me out with a bug in vcg lib. 

Everything is good until I tried to enable the flag "VCG_USE_EIGEN" because it seems more convenient, for example, to multiply a scalar with vcg::Point3f just by typing vcg::Point3f p = 0.3 * vcg::Point3f(1,2,3), which can't be done with deprecated_point3.h

It seems the include code in eigen.h still import 
"#include "../../eigenlib/Eigen/Array" even it's removed in eigen 3.xx.

I am compiling vcglib in Windows 10, branch devel.

**Comment by malomo** [comment]
don't use `VCG_USE_EIGEN`, it is not supported anymore.
