### ISSUE TITLE
vcglib/apps/pivoting/glarea.cpp included an unexisting file. 

### ISSUE THREAD

**Issue by Irene-1990** [cnr-isti-vclab/vcglib#48]
In glarea.cpp, there is a line: 

#include <vcg/space/normal_extrapolation.h> 

However, this normal_extrapolation.h does not exist in the project (it seems to be in an older version of this project). I wonder whether this file is not needed anymore or wrongly be deleted?

**Comment by cignoni** [comment]
unsupported app. Sorry.
