### ISSUE TITLE
copy mesh in vcg lib error

### ISSUE THREAD

**Issue by ZhengzhongSun** [cnr-isti-vclab/vcglib#50]
I want copy one mesh to another mesh. So I find a function in append.h. But when I use it, I find the following description. But I find it will lose some information when copying.
![image](https://user-images.githubusercontent.com/13618800/46145977-3716f580-c294-11e8-989a-c97dde250205.png)
It only copy the attributes in both meshes. But I don't understand the attributes mean. How to copy all of the MeshRight? so I can get the MeshLeft the same with MeshRight.

**Comment by malomo** [comment]
Assuming you are not using custom attributes ([http://vcg.isti.cnr.it/vcglib/attributes.html](url)), if MeshLeft and MeshRight are the same type you won't lose any data.
