### ISSUE TITLE
Bug in Tridecimator and its no texture colors/material problem

### ISSUE THREAD

**Issue by waseemkhan1989** [cnr-isti-vclab/vcglib#56]
Hi,

I tested tridecimator with different models but with every model, I lost all texture colors/material information after the simplification. I tried each and every option available in tridecimator but all in vain. There is also one bug i.e irrespective of which model file I give as input(e.g obj, stl etc), it always output in .ply format. I spotted the bug in tridecimator.cpp file but don't know how to fix it. It is the second last line of this file and it is "vcg::tri::io::ExporterPLY<MyMesh>::Save(mesh,argv[2]);" with the header file  #include <wrap/io_trimesh/export_ply.h>. 

The texture color/material information is really important for me. Any help in this regards would be much appreciated. Thanks

Regards,
Waseem Khan

**Comment by waseemkhan1989** [comment]
@cignoni : Plz, I would really appreciate if you could clear my doubts. Thanks

**Comment by cignoni** [comment]
tridecimator, if I well remember, only handles geometry, so it is a planned feature that it does not save the color.

**Comment by waseemkhan1989** [comment]
Thanks for your prompt reply but what about this bug that " irrespective of which model file I give as input(e.g obj, stl etc), it always output in .ply format. I spotted the bug in tridecimator.cpp file but don't know how to fix it. It is the second last line of this file and it is "vcg::tri::io::ExporterPLY::Save(mesh,argv[2]);" with the header file #include <wrap/io_trimesh/export_ply.h>."
