### ISSUE TITLE
How to use vcglib

### ISSUE THREAD

**Issue by qiji77** [cnr-isti-vclab/vcglib#59]
Compile vcglib meet "C2019"error 严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "public: unsigned __int64 __cdecl vcg::ply::PropDescriptor::memtypesize(void)const " (?memtypesize@PropDescriptor@ply@vcg@@QEBA_KXZ)，该符号在函数 "public: static int __cdecl vcg::tri::io::ImporterPLY<class MyMesh>::Open(class MyMesh &,char const *,class vcg::tri::io::PlyInfo &)" (?Open@?$ImporterPLY@VMyMesh@@@io@tri@vcg@@SAHAEAVMyMesh@@PEBDAEAVPlyInfo@234@@Z) 中被引用	ConsoleApplication4	C:\Users\SuLi\source\repos\ConsoleApplication4\ConsoleApplication4\ConsoleApplication4.obj	1	
What should I do?
and also what should I do if I want to use vcglib in clion?
I 'm a green hand in this,thank you for your help!

**Comment by nodtem66** [comment]
This is linking problem: just add a file `wrap/ply/plylib.cpp` into your project

**Comment by ThreeZhiWang** [comment]
> 
> 
> This is linking problem: just add a file `wrap/ply/plylib.cpp` into your project

正解

**Comment by chenzongyi9708** [comment]
I have another problem here, after adding wrap/ply/plylib.cpp and build,output say generating code without any more output.
