### ISSUE TITLE
Loss of precision when saving ascii PLY

### ISSUE THREAD

**Issue by miquelmassot** [cnr-isti-vclab/vcglib#62]
When saving PLY files as ascii there is a loss in precision, which I believe is caused in  https://github.com/cnr-isti-vclab/vcglib/blob/master/wrap/io_trimesh/export_ply.h#L405 when printf-ing the point coordinates. The modifier `%g` does not specify the number of decimal places, and for large numbers it can lead to losing decimal places. I would like to request to output at least 4 decimals every time.

**Comment by miquelmassot** [comment]
I made a tiny work example to show the problem:

```
#include <iostream>
#include <stdio.h>

int main(int argc, char** argv) {
    double p = 1.234567890123456789;
    double p1 = 1234.567890123456789;
    double p2 = 12345678.90123456789;

    printf("%.*g \n", 16, p);
    printf("%.*g \n", 16, p1);
    printf("%.*g \n", 16, p2);

    printf("%.*g \n", 7, p);
    printf("%.*g \n", 7, p1);
    printf("%.*g \n", 7, p2);

    printf("%.4f \n", p);
    printf("%.4f \n", p1);
    printf("%.4f \n", p2);

    return 0;
}
```

returns 

```
1.234567890123457 
1234.567890123457 
12345678.90123457 
1.234568 
1234.568    <--- Loss of precision here. Only up to millimetres resolution
1.234568e+07 
1.2346 
1234.5679   <--- Good
12345678.9012 
```

**Comment by malomo** [comment]
Use `double` as `ScalarType`, i.e. use `vcg::vertex::Coord3d` in your vertex type definition.
