### ISSUE TITLE
compilation erros for vcglib/wrap/nanoply/nanoply_vcg/nanoply_vcg.pro on linux

### ISSUE THREAD

**Issue by IasonManolas** [cnr-isti-vclab/vcglib#67]
Could not compile neither nanoply_vcg/nanoply_vcg.pro or nanoply_demo/nanoply_demo.pro under linux using both gcc and clang. Haven't checked visualc++ compiler yet. Multiple errors such as:

vcglib/wrap/nanoply/include/nanoply.hpp:2479: error: expected primary-expression before ‘char’
 2479 |       DescriptorHelper<ContainerType, VectorSize, ScalarType>::ReadBinary<char>(

**Comment by malomo** [comment]
Working on it

**Comment by malomo** [comment]
fixed
