### ISSUE TITLE
Vcg import/export error

### ISSUE THREAD

**Issue by KarthikaPooja** [cnr-isti-vclab/vcglib#7]
Hi,
I am newbie to the VCG library. I downloaded the library file from github. I tried to run an example code, but i m getting errors as shown below.

Error	9	error LNK2019: unresolved external symbol "public: unsigned int __thiscall vcg::ply::PropDescriptor::memtypesize(void)const " (?memtypesize@PropDescriptor@ply@vcg@@QBEIXZ) referenced in function "public: static int __cdecl vcg::tri::io::ImporterPLY<class MyMesh>::Open(class MyMesh &,char const *,class vcg::tri::io::PlyInfo &)" (?Open@?$ImporterPLY@VMyMesh@@@io@tri@vcg@@SAHAAVMyMesh@@PBDAAVPlyInfo@234@@Z)	c:\Users\CoitorHP\documents\visual studio 2013\Projects\VcgLibTest\VcgLibTest\Source.obj	VcgLibTest
Error	10	error LNK2019: unresolved external symbol "public: char const * __thiscall vcg::ply::PropDescriptor::stotypename(void)const " (?stotypename@PropDescriptor@ply@vcg@@QBEPBDXZ) referenced in function "public: static int __cdecl vcg::tri::io::ExporterPLY<class MyMesh>::Save(class MyMesh &,char const *,bool,class vcg::tri::io::PlyInfo &,bool (__cdecl*)(int,char const *))" (?Save@?$ExporterPLY@VMyMesh@@@io@tri@vcg@@SAHAAVMyMesh@@PBD_NAAVPlyInfo@234@P6A_NH1@Z@Z)	c:\Users\CoitorHP\documents\visual studio 2013\Projects\VcgLibTest\VcgLibTest\Source.obj	VcgLibTest
Error	11	error LNK2019: unresolved external symbol "private: void __thiscall vcg::ply::PlyFile::compile(class vcg::ply::PlyElement *)" (?compile@PlyFile@ply@vcg@@AAEXPAVPlyElement@23@@Z) referenced in function "public: void __thiscall vcg::ply::PlyFile::SetCurElement(int)" (?SetCurElement@PlyFile@ply@vcg@@QAEXH@Z)	c:\Users\CoitorHP\documents\visual studio 2013\Projects\VcgLibTest\VcgLibTest\Source.obj	VcgLibTest

Please help me to solve this issue. I heard no lib file is needed to run the vcg, but i dont know why i am getting this linker error. Thanks in advance.

**Comment by ganovelli** [comment]
Hi, it looks like

vcglib\wrap\ply\plylib.cpp

wasn't compiled. Please check if it is in your  project files.
cheers,
Fabio

**Comment by KarthikaPooja** [comment]
Hi,
I am sorry , do i need to compile the cpp files ? Could you please tell me how to do that?

**Comment by cignoni** [comment]
Improved the doxygen documentation to remember to use the qmake *.pro files. 
see http://vcg.isti.cnr.it/vcglib/group__code__sample.html
