### ISSUE TITLE
Build fails on arm64, armhf, ppc64el & s390x in Debian/Ubuntu

### ISSUE THREAD

**Issue by rikmills** [cnr-isti-vclab/vcglib#76]
In 2020.02+git200217-1 uploaded to debian unstable and synced to Ubuntu 20.04, builds fail on arm64, armhf, ppc64el & s390x with multiple errors of the form:

`/<<BUILDDIR>>/meshlab-2020.02+git200217/vcglib/vcg/complex/algorithms/create/mc_lookup_table.h:454:5: error: narrowing conversion of ‘-6’ from ‘int’ to ‘char’ [-Wnarrowing]`

lines referred to from 323 to 2556, so most of that header.

https://buildd.debian.org/status/package.php?p=meshlab&suite=sid

https://launchpad.net/ubuntu/+source/meshlab/2020.02+git200217-1

Perhaps a sprinkling of signed char is required.

**Comment by alemuntoni** [comment]
Hi, I added signed char whenever necessary on mc_lookup_table.h, and pushed in the [Meshlab Repo](https://github.com/cnr-isti-vclab/meshlab) the new commit of vcglib. 
Let me know if meshlab builds now.

**Comment by rikmills** [comment]
Sorry for the delay. Yes, that fixed the build on all architectures built in Ubuntu.

Thank you!
