### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lbartoletti** [cnr-isti-vclab/vcglib#86]
Mehslab require vcgilib but latest release is too old for meshlab 2020. 

Please can you create a release at https://github.com/cnr-isti-vclab/vcglib/tree/f7871eed2d54bee704b9f66dc538c921602323cb?

For system packagers this makes the task easier.

**Comment by Stunkymonkey** [comment]
@cignoni or @alemuntoni could you please make a new release?

**Comment by alemuntoni** [comment]
We merged the devel branch into master! 
With the next meshlab version (which is now using the master branch of vcglib), I'll create a new release!

**Comment by alemuntoni** [comment]
New release created! :)

**Comment by kevinsmia1939** [comment]
> New release created! :)

Do you have changelog?

**Comment by alemuntoni** [comment]
@kevinsmia1939 sorry for the late response. Nope, sorry :(
