### ISSUE TITLE
Where is <vcg/space/normal_extrapolation.h> ?

### ISSUE THREAD

**Issue by lyldev** [cnr-isti-vclab/vcglib#87]
I'm working on a project use prev version of VCGLIB, which use 
`#include <vcg/space/normal_extrapolation.h>`
in code. 

But I coud not find this header file in this repo, 
So, I wonder if it is moved, renamed or just deleted ?

**Comment by cignoni** [comment]
moved to  pointcloud_normal.h

https://github.com/cnr-isti-vclab/vcglib/blob/master/vcg/complex/algorithms/pointcloud_normal.h

**Comment by lyldev** [comment]
OK, Thanks for your review.
